### ISSUE TITLE
Plug in CLA bot

### ISSUE THREAD

**Issue by netgusto** [ByteArena/viz#8]
We should plug the CLA bot in all public repositories.

**Comment by xtuc** [comment]
And define the actual text, atm https://gist.github.com/xtuc/f8a80d2aa6dfa46135cb53b123c8159f is used.

**Comment by xtuc** [comment]
- bytearena-cla.md and ByteArena/assets are now linked
- bytearena-cla.md and ByteArena/box2d are now linked
- bytearena-cla.md and ByteArena/bytearena-sdk-javascript are now linked
- bytearena-cla.md and ByteArena/cli are now linked
- bytearena-cla.md and ByteArena/community are now linked
- bytearena-cla.md and ByteArena/docker-healthcheck-watcher are now linked
- bytearena-cla.md and ByteArena/ecs are now linked
- bytearena-cla.md and ByteArena/poly2tri-go are now linked
- bytearena-cla.md and ByteArena/sample-nodejs-agent are now linked
- bytearena-cla.md and ByteArena/viz are now linked
- bytearena-cla.md and ByteArena/schnapps are now linked
